QUOTES = [
    "The only true wisdom is in knowing you know nothing.",
    "To be or not to be, that is the question.",
    "All that glitters is not gold.",
    "The early bird catches the worm.",
    "An investment in knowledge pays the best interest.",
    "Tell me and I forget, teach me and I may remember.",
    "By failing to prepare, you are preparing to fail.",
    "The secret of getting ahead is getting started.",
    "Better three hours too soon than a minute too late.",
    "To know oneself is the beginning of all wisdom.",
    "The unexamined life is not worth living.",
    "Cowards die many times before their deaths.",
    "Some are born great, some achieve greatness, some have greatness thrust upon them.",
    "Travel is fatal to prejudice, bigotry, and narrow-mindedness.",
    "What lies behind us is nothing to what lies before us.",
    "The only way to do great work is to love what you do.",
    "Life is what happens when you are busy making other plans.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It is during our darkest moments that we must focus on the light.",
    "Do not go where the path may lead, go instead where there is no path.",
    "The only impossible journey is the one you never begin.",
    "Success is not final, failure is not fatal.",
    "Believe you can and you are halfway there.",
    "The best time to plant a tree was twenty years ago.",
    "Whether you think you can or you think you cannot, you are right.",
    "Our greatest weakness lies in giving up.",
    "Keep your face always toward the sunshine.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Do what you can, with what you have, where you are.",
    "Great minds discuss ideas, average minds discuss events.",
    "The mind is everything. What you think, you become.",
    "Your time is limited, do not waste it living someone else's life.",
    "The only thing we have to fear is fear itself.",
    "Ask not what your country can do for you.",
    "I have a dream that one day this nation will rise up.",
    "Float like a butterfly, sting like a bee.",
    "Life is ten percent what happens to you and ninety percent how you react.",
    "If you judge people, you have no time to love them.",
    "Two things are infinite: the universe and human stupidity.",
    "Imagination is more important than knowledge.",
    "Logic will get you from A to B, imagination will get you everywhere.",
    "The only real mistake is the one from which we learn nothing.",
    "In the middle of difficulty lies opportunity.",
    "Never in the field of human conflict was so much owed by so many.",
    "It was the best of times, it was the worst of times.",
    # Add these 150 quotes to your existing QUOTES list in quotes.py

    "The best way out is always through.",
    "Nothing great was ever achieved without enthusiasm.",
    "What we think, we become.",
    "Excellence is not a skill, it is an attitude.",
    "Action is the foundational key to all success.",
    "Well done is better than well said.",
    "A journey of a thousand miles begins with a single step.",
    "Knowledge speaks, but wisdom listens.",
    "Change your thoughts and you change your world.",
    "The way to get started is to quit talking and begin doing.",
    "Don't watch the clock; do what it does. Keep going.",
    "The harder I work, the luckier I get.",
    "Opportunities don't happen, you create them.",
    "Try not to become a person of success but of value.",
    "Great things never come from comfort zones.",
    "Dream big and dare to fail.",
    "Success usually comes to those who are too busy to be looking.",
    "The road to success is always under construction.",
    "I find that the harder I work, the more luck I have.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "If you are not willing to risk the usual you will settle.",
    "All our dreams can come true if we have the courage.",
    "Don't be afraid to give up the good to go for the great.",
    "People who are crazy enough to think they can change the world do.",
    "Knowing is not enough; we must apply. Willing is not enough; we must do.",
    "I have not failed. I've just found ten thousand ways that won't work.",
    "A person who never made a mistake never tried anything new.",
    "The only person you are destined to become is the person you decide.",
    "What you do today can improve all your tomorrows.",
    "The only way to achieve the impossible is to believe it is possible.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Everything you've ever wanted is on the other side of fear.",
    "We can easily forgive a child who is afraid of the dark.",
    "Teach thy tongue to say I do not know and thou shalt progress.",
    "Live as if you were to die tomorrow. Learn as if to live forever.",
    "An unexamined life is not worth living.",
    "Turn your wounds into wisdom.",
    "Real knowledge is to know the extent of one's ignorance.",
    "The roots of education are bitter, but the fruit is sweet.",
    "Education is the most powerful weapon which you can use to change the world.",
    "The beautiful thing about learning is that nobody can take it away.",
    "Education is not preparation for life; education is life itself.",
    "The more that you read, the more things you will know.",
    "Learning never exhausts the mind.",
    "Change is the end result of all true learning.",
    "Education is the passport to the future.",
    "The capacity to learn is a gift.",
    "Intelligence plus character, that is the goal of true education.",
    "Education is not the filling of a pail but the lighting of a fire.",
    "The expert in anything was once a beginner.",
    "Courage is not the absence of fear but triumph over it.",
    "You miss one hundred percent of the shots you don't take.",
    "I've learned that people will forget what you said.",
    "The best revenge is massive success.",
    "A champion is defined not by their wins but by how they recover.",
    "To live is the rarest thing in the world. Most people just exist.",
    "If you want to lift yourself up, lift up someone else.",
    "Certain things catch your eye, but pursue only those that capture the heart.",
    "It is never too late to be what you might have been.",
    "A man is but the product of his thoughts.",
    "If you can dream it, you can do it.",
    "The mind is not a vessel to be filled but a fire.",
    "Act as if what you do makes a difference. It does.",
    "Success is not how high you have climbed but how you make a difference.",
    "What we achieve inwardly will change outer reality.",
    "Happiness is not something ready made. It comes from your own actions.",
    "If you want to go fast, go alone. If you want to go far, go together.",
    "The greatest glory in living lies not in never falling.",
    "Life is either a daring adventure or nothing at all.",
    "Spread love everywhere you go.",
    "When you reach the end of your rope, tie a knot and hang on.",
    "Always remember that you are absolutely unique. Just like everyone else.",
    "Don't judge each day by the harvest you reap but by the seeds.",
    "The future belongs to those who prepare for it today.",
    "Quality is not an act, it is a habit.",
    "We are what we repeatedly do.",
    "It is not length of life, but depth of life.",
    "Get busy living or get busy dying.",
    "You only live once, but if you do it right, once is enough.",
    "Never let the fear of striking out keep you from playing the game.",
    "Money and success don't change people; they merely amplify who they are.",
    "Not how long, but how well you have lived is the main thing.",
    "The whole secret of a successful life is to find out what is.",
    "In order to write about life first you must live it.",
    "Life is made of ever so many partings welded together.",
    "Your work is going to fill a large part of your life.",
    "Keep smiling, because life is a beautiful thing.",
    "Life is short, and it is up to you to make it sweet.",
    "The best and most beautiful things in the world cannot be seen.",
    "It is during our darkest moments that we must focus to see the light.",
    "Whoever is happy will make others happy too.",
    "Do not let making a living prevent you from making a life.",
    "Go confidently in the direction of your dreams.",
    "When I let go of what I am, I become what I might be.",
    "Everything has beauty, but not everyone can see.",
    "How wonderful it is that nobody need wait a single moment.",
    "When everything seems to be going against you, remember that the airplane takes off.",
    "It's not whether you get knocked down, it's whether you get up.",
    "Limit your always and your nevers.",
    "Nothing is impossible, the word itself says I'm possible.",
    "There are no shortcuts to any place worth going.",
    "I alone cannot change the world, but I can cast a stone.",
    "What lies behind you and what lies in front of you pales.",
    "Strive not to be a success, but rather to be of value.",
    "The only impossible journey is the one you never start.",
    "In this life we cannot do great things. We can do small things.",
    "Change will not come if we wait for some other person.",
    "Perfection is not attainable, but if we chase perfection we catch excellence.",
    "Life shrinks or expands in proportion to one's courage.",
    "If I cannot do great things, I can do small things in a great way.",
    "Never bend your head. Always hold it high. Look the world straight.",
    "Nothing will work unless you do.",
    "Do one thing every day that scares you.",
    "Too many of us are not living our dreams because we are living our fears.",
    "I didn't fail the test. I just found ways to do it wrong.",
    "Whether you think you can or can't, either way you are right.",
    "If you're going through hell, keep going.",
    "Be yourself; everyone else is already taken.",
    "A room without books is like a body without a soul.",
    "Be the change that you wish to see in the world.",
    "No one can make you feel inferior without your consent.",
    "If you tell the truth, you don't have to remember anything.",
    "Be who you are and say what you feel.",
    "You only live once, but if you do it right, once is enough.",
    "To be yourself in a world that is constantly trying is the greatest accomplishment.",
    "Imperfection is beauty, madness is genius.",
    "Yesterday is history, tomorrow is a mystery, today is a gift.",
    "It is better to be hated for what you are.",
    "There are only two ways to live your life. One is as though nothing.",
    "Darkness cannot drive out darkness: only light can do that.",
    "The weak can never forgive. Forgiveness is the attribute of the strong.",
    "Do not dwell in the past, do not dream of the future.",
    "Success is not final, failure is not fatal: it is the courage to continue.",
    "It is better to remain silent at the risk of being thought a fool.",
    "You must be the change you wish to see in the world.",
    "I have not failed. I've found ten thousand ways that won't work.",
    "A successful man is one who can lay a firm foundation.",
    "Believe in yourself. You are braver than you think.",
    "The only thing standing between you and your goal is the story.",
    "When one door of happiness closes, another opens.",
    "The difference between winning and losing is most often not quitting.",
    "You are never too old to set another goal.",
    "If you want something you have never had, you must do something.",
    "Whatever the mind of man can conceive and believe, it can achieve.",
    "The future depends on what you do today.",
    "A goal is not always meant to be reached.",
    "You can never cross the ocean until you have the courage.",
    "Believe and act as if it were impossible to fail.",
    "What's money? A man is a success if he gets up in the morning.",
    "The starting point of all achievement is desire.",
    "All progress takes place outside the comfort zone.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "The best preparation for tomorrow is doing your best today.",
    "Get in the zone, AutoZone!",
]