QUOTES = [
    "The only true wisdom is in knowing you know nothing.",
    "To be or not to be, that is the question.",
    "All that glitters is not gold.",
    "The early bird catches the worm.",
    "An investment in knowledge pays the best interest.",
    "Tell me and I forget, teach me and I may remember.",
    "By failing to prepare, you are preparing to fail.",
    "The secret of getting ahead is getting started.",
    "Better three hours too soon than a minute too late.",
    "To know oneself is the beginning of all wisdom.",
    "The unexamined life is not worth living.",
    "Cowards die many times before their deaths.",
    "Some are born great, some achieve greatness, some have greatness thrust upon them.",
    "Travel is fatal to prejudice, bigotry, and narrow-mindedness.",
    "What lies behind us is nothing to what lies before us.",
    "The only way to do great work is to love what you do.",
    "Life is what happens when you are busy making other plans.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It is during our darkest moments that we must focus on the light.",
    "Do not go where the path may lead, go instead where there is no path.",
    "The only impossible journey is the one you never begin.",
    "Success is not final, failure is not fatal.",
    "Believe you can and you are halfway there.",
    "The best time to plant a tree was twenty years ago.",
    "Whether you think you can or you think you cannot, you are right.",
    "Our greatest weakness lies in giving up.",
    "Keep your face always toward the sunshine.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Do what you can, with what you have, where you are.",
    "Great minds discuss ideas, average minds discuss events.",
    "The mind is everything. What you think, you become.",
    "Your time is limited, do not waste it living someone else's life.",
    "The only thing we have to fear is fear itself.",
    "Ask not what your country can do for you.",
    "I have a dream that one day this nation will rise up.",
    "Float like a butterfly, sting like a bee.",
    "Life is ten percent what happens to you and ninety percent how you react.",
    "If you judge people, you have no time to love them.",
    "Two things are infinite: the universe and human stupidity.",
    "Imagination is more important than knowledge.",
    "Logic will get you from A to B, imagination will get you everywhere.",
    "The only real mistake is the one from which we learn nothing.",
    "In the middle of difficulty lies opportunity.",
    "Never in the field of human conflict was so much owed by so many.",
    "It was the best of times, it was the worst of times."
]